### ISSUE TITLE
Release Date

### ISSUE THREAD

**Issue by blackearth2014** [NikolaiVChr/Autinn#1]
When is the release date?

**Comment by NikolaiVChr** [comment]
I reckon final release will coincide with Rack v1.0

It still needs lots of love.

**Comment by NikolaiVChr** [comment]
If you are on Windows, you can try out the pre-release build 0.5.1.1. Just made it.

I would very much like some feedback on how you think it performs. Both CPU-wise and sound.

https://github.com/NikolaiVChr/Autinn/releases/download/0.5.1.1/Autinn-win-0.5.1.1.zip

**Comment by blackearth2014** [comment]
I have windows and I will test it for you on my next comp. Be on the look out on my vcvrack playlist at https://www.youtube.com/playlist?list=PLKq_Gnn6tV4qxAcLmio5-v7xY1PKQZocm. I will mention your plugin when I use it.

Thanks foe the first test module.

**Comment by NikolaiVChr** [comment]
Your welcome, hope you are able to get something nice out of it. :)

**Comment by blackearth2014** [comment]
Tip you have operating tips on what knobs does what.

**Comment by blackearth2014** [comment]
By the way, are you planning on adding a CV knob doe the voltage parameter?

**Comment by NikolaiVChr** [comment]
**Tip**: I like the sound best when the voltage is turned at least so low that the red light next to the out port is not blinking or turned on.

The small knobs next to the CV in-ports is for adjusting how much influence the CV signals have.

Since its simulating transistors, they react slightly different when heated up, so I have added the temperature knob for that.

The small knob under voltage is for fine adjustment.

I might add a CV to the voltage control, I will think about it.

Cutoff is where its attenuating approx 12dB. And resonance is enhancement of the signal around that frequency.

**Comment by blackearth2014** [comment]
Cool Breeze 

This is your season
Omar Brown
Blessed House Media

On Jan 13, 2018, at 1:28 AM, Nikolai V. Chr. <notifications@github.com> wrote:

Tip: I like the sound best when the voltage is turned at least so low that the red light next to the out port is not blinking or turned on.

The small knobs next to the CV in-ports is for adjusting how much influence the CV signals have.

Since its simulating transistors, they react slightly different when heated up, so I have added the temperature knob for that.

The small knob under voltage is for fine adjustment.

I might add a CV to the voltage control, I will think about it.

Cutoff is where its attenuating approx 12dB. And resonance is enhancement of the signal around that frequency.

**Comment by NikolaiVChr** [comment]
:)

I have updated the release file again. Also have put in an oscillator with a fixed waveform I made for testing the filter, might be useful for something. Its quite simple though; just a frequency knob, and CV.

**Comment by blackearth2014** [comment]
The VCO sound good for grunge and other ideas. It has sound serious output compared to Befaco EvenVCO and Vult Vessek. Some of the other VCO's doesn't seem to have the output to drive the filter to maintain a driving output. The fundamental just get lost in volume as soon as you plug it in. Is that suppose to happen? Does your filter require to be driven or is that the fundamental VCO's doesn't have what it takes.

**Comment by blackearth2014** [comment]
By the way, besides the VCO addition, what changed in the filter?

**Comment by NikolaiVChr** [comment]
Befaco EvenVCO is +-7V
Vult Vessek is around the same depending on your waveform
Autinn Oxcart is +-5V

Stronger inputs will be attenuated more if you had the voltage knobs dialed high/medium.
If you think there is not enough power on the filter out, then try lower the input signal strength, and amplify the output.

To understand your issue with fundamentals being lost in volume, I have to know more about what your setup is. It might be that when you have a high resonance, due to the way resonance is made with a feedback that it will attenuate frequencies that is not the resonance frequency. If that is your issue, then I might not be able to fix it. Does it also happen when you use no resonance?

Don't think I changed the filter, I just added the Oxcart. But I just made another release, where I did change the filter.

On the github main Autinn page, I have now added a changelog to the readme so you can see what I changed.

**Comment by blackearth2014** [comment]
I think its me getting to know your Module and module voltage outputs.

**Comment by NikolaiVChr** [comment]
I have replaced the Voltage knobs with a kind of drive knob. Is easier to adjust.
Also made some other improvements.

**Comment by blackearth2014** [comment]
Cool Breeze!!!

**Comment by blackearth2014** [comment]
I am digging the updated Retri Filter. It sound really nice.

**Comment by blackearth2014** [comment]
Nikolai,

The Retri filter Cutoff and Res sounds good to me, but I don’t here a different in the temperature knob when adjusted. Also, is the Drive knob based off the Res knob.

This is your season
Omar Brown
Blessed House Media

On Jan 15, 2018, at 5:50 PM, Nikolai V. Chr. <notifications@github.com> wrote:

I have replaced the Voltage knobs with a kind of drive knob. Is easier to adjust.
Also made some other improvements.

**Comment by NikolaiVChr** [comment]
The temperature knob is very subtle, I only tried 1 waveform where I really could hear it, and it was a small effect.

The drive knob adjusts the voltage going in the to the filter, and then does the opposite adjustment on the output of the filter. Yes it affects resonance peak shape, and attenuation in general, due to the non-linearity of the filter.

**Comment by blackearth2014** [comment]
I have no clue what non-linearity  means or how it affects filters, but your filter still sounds nice.
